### ISSUE TITLE
Activation Preference is Empty in Report

### ISSUE THREAD

**Issue by DelectableMechanisations** [cunninghamp/Test-ExchangeServerHealth.ps1#10]
This is only a minor issue but the line of code:
`$pref = ($database | Select-Object -ExpandProperty ActivationPreference | Where-Object {$_.Key -eq $mailboxserver}).Value`

Should be replaced with:
`$pref = ($database | Select-Object -ExpandProperty ActivationPreference | Where-Object {$_.Key.ToString().ToUpper() -eq $mailboxserver.ToUpper()}).Value`

This is because the Key property of ActivationPreference is case sensitive and `$pref` will be empty if `$mailboxserver` uses a different case.

**Without code change (Activation Preference is empty)**
![activation preference empty](https://cloud.githubusercontent.com/assets/15990297/14480514/fc4319a4-017d-11e6-8515-9b634ccc982a.PNG)

**With code change (Activation Preference is populated)**
![activation preference populated](https://cloud.githubusercontent.com/assets/15990297/14480516/014eb476-017e-11e6-83ef-dd1115158a87.PNG)

Love your work Paul

**Comment by Caos1980** [comment]
Hi, i solved with another operator

"-eq $mailboxserver" with "-like "*$mailboxserver*"

I replace every command with "-like "*$mailboxserver*"

It seems that the operator "-eq" requires case sensitive value

Now working fine for me

Regards

**Comment by cunninghamp** [comment]
Yep that would make sense. I'll patch that and use -ieq instead of -eq.
