### ISSUE TITLE
Issue with remoting session when script is ran on the same server it is checking

### ISSUE THREAD

**Issue by brolifen** [cunninghamp/Test-ExchangeServerHealth.ps1#14]
When the script is ran on the server it it checking when it reaches the mailflow test and tries to make a ps remoting sessions it throws the following error:

The WinRM client received an HTTP bad request status (400)

In order to fix this I added "-Authentication Kerberos" to the new pssession line in the mailflow test function.

**Comment by cunninghamp** [comment]
Unable to repro. This test will be redeveloped in a future version.
