### ISSUE TITLE
The script file is recognized as bin

### ISSUE THREAD

**Issue by it-praktyk** [cunninghamp/Test-ExchangeServerHealth.ps1#6]
Hi,
the script file was saved uncorrectly (?) and is not recognized as a text file but as the bin type file.

![2015-12-02 10_47_05-v1 15 cunninghamp_test-exchangeserverhealth ps1 6173fe7](https://cloud.githubusercontent.com/assets/4910261/11527584/2908da5a-98e2-11e5-960e-53910b994993.jpg)

Some GitHub functions - e.g. displaying changes for commits - don't work correctly.

Probably the content of file need to be copied to the new text file in normal text/developer editor, the existing file in the repository overwriten.

Thank you!

**Comment by cunninghamp** [comment]
I believe this is now fixed in master and development branches.
