### ISSUE TITLE
Recovery RDB

### ISSUE THREAD

**Issue by mrenergy99** [cunninghamp/Test-ExchangeServerHealth.ps1#8]
When I have an RDB active it does not show in the report which is perfect. If I dismount the RDB then it does show up in the report.  Is there a change I can make to just excluded the RDB's from the report regardless of the status there in?

**Comment by cunninghamp** [comment]
Thanks for raising this issue. It looks like a few of the Get-MailboxDatabase calls in the script don't have the filtering to exclude recovery databases.

```
Where {$_.Recovery -ne $true}
```

Do a find on that cmdlet and add the filter yourself for now, or add the recovery database name to ignorelist.txt to ignore it.

I'll fix the bug in the near future.

**Comment by cunninghamp** [comment]
Fixed in development

**Comment by cunninghamp** [comment]
Fixed in release https://github.com/cunninghamp/Test-ExchangeServerHealth.ps1/releases/tag/V1.16
