### ISSUE TITLE
$serverinfoservices is null

### ISSUE THREAD

**Issue by letal1609** [cunninghamp/Test-ExchangeServerHealth.ps1#9]
First of all, thank you for your power shell script. I am using you it but, it is giving me error.

$serverinfoservices is null
![capture2](https://cloud.githubusercontent.com/assets/6105595/14314313/107f16ea-fbe6-11e5-85a1-6ec0f0ff8a57.PNG)

**Comment by cunninghamp** [comment]
I've just updated the README.MD with some info about modifying the script for different languages.

**Comment by letal1609** [comment]
Thank you. My issue is solved.
